import type { ProjectMemoryExportOptions, ProjectOverviewResponse } from "../types";

export const overviewFixture: ProjectOverviewResponse = {
  project: "memory",
  service_status: "ok",
  database_status: "ok",
  memory_entries_total: 0,
  active_memories: 0,
  archived_memories: 0,
  high_confidence_memories: 0,
  medium_confidence_memories: 0,
  low_confidence_memories: 0,
  recent_memories_7d: 0,
  recent_captures_7d: 0,
  raw_captures_total: 0,
  uncurated_raw_captures: 0,
  tasks_total: 0,
  sessions_total: 0,
  curation_runs_total: 0,
  last_memory_at: null,
  last_curation_at: null,
  last_capture_at: null,
  oldest_uncurated_capture_age_hours: null,
  embedding_chunks_total: 0,
  fresh_embedding_chunks: 0,
  stale_embedding_chunks: 0,
  missing_embedding_chunks: 0,
  embedding_spaces_total: 0,
  active_embedding_provider: null,
  active_embedding_model: null,
  pending_replacement_proposals: 0,
  top_tags: [],
  top_files: [],
  memory_type_breakdown: [],
  source_kind_breakdown: [],
  automation: null,
  watchers: null,
};

export const bundleOptionsFixture: ProjectMemoryExportOptions = {
  include_archived: false,
  include_tags: true,
  include_relations: true,
  include_source_file_paths: false,
  include_git_commits: false,
  include_source_excerpts: false,
};
